apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- server/.gitkeep
- service.yaml
namespace: go-webserver
images:
- name: deploy/image
  newName: luizfernadomarques/go-webserver
  newTag: 918808dbaf24f188544c80deff0ab04c207d8377
