apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- server/.gitkeep
- service.yaml
namespace: go-webserver
images:
- name: deploy/image
  newName: luizfernadomarques/go-webserver
  newTag: 18019112ca7fd8e06b4d4f2ec230c586eaab56a1
