apiVersion: apps/v1
kind: Deployment
metadata:
  name: xx-samsung
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xx-samsung
  template:
    metadata:
      labels:
        app: xx-samsung
    spec:
      containers:
        - name: xx-samsung
          image: deploy/image
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: xx-samsung
