apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- service.yaml
namespace: xx-samsung
images:
- name: deploy/image
  newName: luizfernadomarques/api-gateway-fernando
  newTag: 62d3f9865c52924d8b87d8bae548106283949cd1
