apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- service.yaml
namespace: xx-gympass
images:
- name: deploy/image
  newName: luizfernadomarques/api-gateway-fernando
  newTag: 900b062106101e55505157616d08ef36be50fa91
