apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: go-webserver
images:
- name: deploy/image
  newName: luizfernandomarques/go-webserver
  newTag: "123"
