name: Pull Request

on:
  pull_request:

jobs:
  conftest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Check configuration errors
        run: docker run --rm -v ${{ github.workspace }}:/project openpolicyagent/conftest test -p policy.rego --combine deployments/production

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Run Lint
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KUBERNETES_KUBEVAL_OPTIONS: "--ignore-missing-schemas"
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_KUBERNETES_KUBEVAL: true
          VALIDATE_YAML: true